image:
  - 'fedora-bootc'
  - '*.json'
  - '*.yaml'
  - '*.toml'
  - '*.pub'
builder:
  - 'Dockerfile'
  - '.github/workflows/pr.yml'
ci:
  - '.github/workflows/ci.yml'
  - '.github/workflows/build-push.yml'
