name: Continuous integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build base image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: localhost/almalinux-bootc
          containerfiles: |
            Containerfile
          oci: 'true'
          extra-args: |
            --security-opt=label=disable
            --cap-add=all
            --device /dev/fuse
