name: Continuous Integration

on:
  push:
    branches:
      - main
      - v[0-9]+

jobs:
  check-changes:
    name: Check changes since last commit
    runs-on: ubuntu-24.04
    outputs:
      image: ${{ steps.changes.outputs.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Check changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: ./.github/paths-filter.yml

  gen-metadata:
    name: Generate metadata
    needs: check-changes
    if: ${{ needs.check-changes.outputs.image == 'true' }}
    runs-on: ubuntu-24.04
    outputs:
      tags: ${{ steps.metadata.outputs.tags }}
      version: ${{ steps.metadata.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Validate release branch version
        if: ${{ github.ref_name != 'main' }}
        run: |
          #!/bin/bash
          set -xeo pipefail

          releasever=$(yq '.releasever' almalinux-bootc-version.yaml)
          if [[ ${GITHUB_REF_NAME#v*} != ${releasever%%.*} ]]
          then
            echo "Release branch should match major version in manifest"
            exit 1
          fi

      - name: Generate metadata
        id: metadata
        run: |
          #!/bin/bash
          set -xeo pipefail

          releasever=$(yq '.releasever' almalinux-bootc-version.yaml)
          echo "version=${releasever}+$GITHUB_SHA" >> "$GITHUB_OUTPUT"
          tags="$GITHUB_SHA $GITHUB_REF_NAME v$releasever"

          if [[ $GITHUB_REF_NAME == "main" ]]
          then
            tags+=" v${releasever%%.*}"
          fi

          echo "tags=$tags" >> "$GITHUB_OUTPUT"

  ci-image:
    name: CI image
    uses: ./.github/workflows/build-push.yml
    with:
      image: almalinux-ci
      tags: ${{ needs.gen-metadata.outputs.tags }}
      version: ${{ needs.gen-metadata.outputs.version }}
    secrets: inherit
    needs: gen-metadata
    permissions:
      packages: write
      security-events: write
