name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  gen-metadata:
    name: Generate metadata
    runs-on: ubuntu-24.04
    outputs:
      tags: ${{ steps.metadata.outputs.tags }}
      version: ${{ steps.metadata.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Validate tag version
        run: |
          #!/bin/bash
          set -xeo pipefail

          releasever=$(yq '.releasever' almalinux-bootc-version.yaml)
          if [[ ${GITHUB_REF_NAME%.*} != "v${releasever}" ]]
          then
            echo "Tag version should match major version in manifest"
            exit 1
          fi

      - name: Generate metadata
        id: metadata
        run: |
          #!/bin/bash
          set -xeo pipefail

          releasever=$(yq '.releasever' almalinux-bootc-version.yaml)
          echo "version=${GITHUB_REF_NAME#v*}" >> "$GITHUB_OUTPUT"
          tags="${GITHUB_REF_NAME} ${GITHUB_REF_NAME%.*} ${GITHUB_REF_NAME%%.*}"
          echo "tags=$tags" >> "$GITHUB_OUTPUT"

  release-image:
    name: Release image
    uses: ./.github/workflows/build-push.yml
    with:
      image: almalinux
      tags: ${{ needs.gen-metadata.outputs.tags }}
      version: ${{ needs.gen-metadata.outputs.version }}
    secrets: inherit
    needs: gen-metadata
    permissions:
      packages: write
      security-events: write

  release:
    name: Create GitHub release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Create Github release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          generate_release_notes: true
          draft: true
          files: cosign.pub
