name: Vulnerability scan

on:
  schedule:
    - cron: 45 5 * * *
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}/bootc
  RELEASE_IMAGE: almalinux
  RELEASE_TAGS: "v9"
  CI_IMAGE: almalinux-ci
  CI_TAGS: "main"

jobs:
  images:
    name: Generate a list of release and CI images
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.list.outputs.images }}
    steps:
      - name: Generate image list
        id: list
        run: |
          #!/bin/bash
          set -xeo pipefail

          images=""
          for tag in $RELEASE_TAGS
          do
            images+="${REGISTRY}/${RELEASE_IMAGE}:${tag} "
          done
          
          for tag in $CI_TAGS
          do
            images+="${REGISTRY}/${CI_IMAGE}:${tag} "
          done

          images=$(echo $images | sed 's/\s+$//' | jq --raw-input 'split(" ")' | jq -r tostring)
          echo "images=$images" >> "$GITHUB_OUTPUT"

  scan:
    name: Scan container images and upload SARIF file
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    needs: images
    strategy:
      matrix:
        image: ${{ fromJSON(needs.images.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup Cosign
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0

      - name: Verify image
        id: verify
        run: |
          #!/bin/bash

          set -xeo pipefail
          
          digest=$(cosign verify --key cosign.pub ${{ matrix.image }} | jq -r '.[0].critical.image."docker-manifest-digest"')
          echo "digest=$digest" >> "$GITHUB_OUTPUT"

      - name: Get image metadata
        id: metadata
        run: |
          #!/bin/bash

          set -xeo pipefail

          image_no_tag=$(echo ${{ matrix.image }} | cut -f1 -d ':')
          commit=$(skopeo inspect docker://${image_no_tag}@${{ steps.verify.outputs.digest }} | jq -r '.Labels."org.opencontainers.image.revision"')
          tag=refs/tags/v$(skopeo inspect docker://${image_no_tag}@${{ steps.verify.outputs.digest }} | jq -r '.Labels."org.opencontainers.image.version"')

          echo "commit=$commit" >> "$GITHUB_OUTPUT"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Verify attestation and extract SBOM
        run: |
          #!/bin/bash

          set -xeo pipefail

          cosign verify-attestation --key cosign.pub ${{ matrix.image }} | jq -r .payload | base64 -d | jq -r .predicate.Data > sbom.syft.json

      - name: Scan SBOM with Grype
        uses: anchore/scan-action@3343887d815d7b07465f6fdcd395bd66508d486a # v3.6.4
        id: scan
        with:
          sbom: sbom.syft.json
          fail-build: false
          output-format: sarif
          only-fixed: true
          grype-version: v0.78.0

      - name: Upload image scan results to GitHub
        uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # v3.25.8
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
          ref: ${{ steps.metadata.outputs.tag }}
          sha: ${{ steps.metadata.outputs.commit }}
