name: Scheduled Release

on:
  workflow_dispatch:
  schedule:
    - cron: 15 3 * * 2

jobs:
  check-updates:
    name: Check available updates since last release
    if: ${{ github.event_name != 'push' }}
    outputs:
      available: ${{ steps.updates.outputs.available }}
      timestamp: ${{ steps.updates.outputs.timestamp }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Check updates
        id: updates
        run: |
          #!/bin/bash

          set -xeo pipefail
          releasever=$(yq '.releasever' 'almalinux-bootc.yaml')
          image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          digest=$(cosign verify --key cosign.pub ${image}:${releasever} | jq -r '.[0]["critical"]["image"]["docker-manifest-digest"]')

          podman run --rm ${image}@${digest} dnf check-upgrade
          if [[ $? -eq 100 ]]
          then
            echo "available='true'" >> "$GITHUB_OUTPUT"
          else
            echo "available='false'" >> "$GITHUB_OUTPUT"
          fi
          echo "timestamp=$(date +%s)" >> "$GITHUB_OUTPUT"

  build-publish:
    uses: ./.github/workflows/release.yml
    with:
      tag-suffixes: ${{ needs.check-updates.outputs.timestamp }}
    needs: check-updates
    if: ${{ needs.check-updates.outputs.available == 'true' }}
    permissions:
      packages: write
